<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Application;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNew()
    {
        return $this->findBy(array(
            'status' => Application::STATUS_NEW
        ), array(
            'createdAt' => 'DESC'
        ));
    }
}
