---
- name: install php
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-cli
    - php5-common
    - php5-intl
    - php5-mysql
    - php5-mcrypt
    - php5-curl
    - php5-gd
  notify:
    - reload apache
