---
- name: Install xDebug
  sudo: yes
  apt: pkg=php5-xdebug state=latest

- name: Configure xdebug
  sudo: yes
  lineinfile: dest=/etc/php5/apache2/conf.d/20-xdebug.ini line="{{ item }}"
  with_items:
    - xdebug.max_nesting_level = 250
    - xdebug.remote_autostart=on
    - xdebug.remote_enable = on
    - xdebug.remote_handler = dbgp
    - xdebug.remote_mode = req
    - xdebug.remote_port = 9000
    - xdebug.remote_host = 33.33.33.1
    - xdebug.idekey = "PHPSTORM"
